"""
Hub-side query normalizer. Run once before intent classification and embedding.
Handles duplicate words and known STT artifacts that may survive kiosk-side processing.
"""
import re

_DUPLICATE_WORD = re.compile(r"\b(\w+)( \1)+\b", re.IGNORECASE)
_WHITESPACE = re.compile(r"\s+")

_HUB_CORRECTIONS = {
    "where where": "where",
    "i i": "i",
    "the the": "the",
    "is is": "is",
    "twelve noon": "12 noon",
    "seven am": "7 am",
    "seven a m": "7 am",
    "six pm": "6 pm",
    "six p m": "6 pm",
    "nine am": "9 am",
    "nine pm": "9 pm",
    "eight am": "8 am",
    "eight pm": "8 pm",
    # Domain-specific phrasing normalizations for shelter questions.
    # These help align translated / spoken variants with how KB articles are titled.
    "where is food being served": "where is food served",
    "where is the food being served": "where is food served",
    "where do we eat": "where is food served",
    "where can i eat": "where is food served",
    "where is food served here": "where is food served",
    "how do i register": "how do i register for the shelter",
    "how do i sign up": "how do i register for the shelter",
    "where do i sign up": "how do i register for the shelter",
    "where is registration": "where do i register",
    "where do i register": "where do i register",
    "where is medical": "where is the medical area",
    "where is the clinic": "where is the medical area",
    "i need medical": "i need medical help",
    "i need a doctor": "i need medical help",
    "where can i sleep": "where is the sleeping area",
    "where do we sleep": "where is the sleeping area",
    "where are the beds": "where is the sleeping area",
    # Common English misspellings / variants in evacuation center context
    "evacuation centre": "evacuation center",
    "shelter center": "shelter",
    "registration desk": "registration",
    "register desk": "registration",
    "check in": "check-in",
    "checkin": "check-in",
    "intake desk": "intake",
    "wrist band": "wristband",
    "first aid": "medical station",
    "med station": "medical station",
    "rest room": "restroom",
    "bath room": "bathroom",
    "toilet": "restroom",
    "washroom": "restroom",
    "shower room": "showers",
    "charging station": "charging",
    "phone charging": "charging",
    "wifi": "wi-fi",
    "wi fi": "wi-fi",
    "lost and found": "lost person",
    "annoucements": "announcements",
    "announcments": "announcements",
    "volunter": "volunteer",
    "donation": "donations",
    "supplies distribution": "distribution",
    "relief goods": "distribution",
    "pickup": "distribution",
    "bus schedule": "transportation",
    "shuttle": "transportation",
    "pet area": "pets",
    "child care": "family services",
    "curfew": "curfew",
    "quiet hours": "quiet hours",
    "lights out": "quiet hours",
    "rules": "rules",
    "policies": "rules",
    "sop": "procedures",
    "sops": "procedures",
    "standard operating procedure": "procedures",
    "missing child": "lost person",
    "missing kid": "lost person",
    "lost child": "lost person",
    "lost kid": "lost person",
    "family reunification": "reunification",
    "reunite": "reunification",
    "pharmacy": "medical station",
    "medicine": "medical station",
    "security": "safety",
    "evac route": "evacuation route",
    "evacuation route": "evacuation route",
    "hazard": "safety",
    "power outage": "power",
    "electricity": "power",
    "charging area": "charging",
    "mental health": "mental health",
    "counseling": "mental health",
    "psychological": "mental health",
    "medical help": "medical station",
    "vaccination": "vaccination",
    "vaccines": "vaccination",
    "legal aid": "legal assistance",
    "legal help": "legal assistance",
    "lawyer": "legal assistance",
    "pet reunification": "reunification",
    "donation drop off": "donations",
    "donation drop-off": "donations",
    "donation hours": "donations",
    "distribution hours": "distribution",
    "food distribution schedule": "food schedule",
    "food distribution time": "food schedule",
    "food distribution times": "food schedule",
    "food distribution hours": "food schedule",
    "food distribution schedule here": "food schedule",
    "meal distribution schedule": "food schedule",
    "meal distribution time": "food schedule",
    "meal distribution times": "food schedule",
    "meal distribution hours": "food schedule",
    "schedule for food distribution": "food schedule",
    "schedule of food distribution": "food schedule",
    "schedule for meals": "food schedule",
    "schedule of meals": "food schedule",
    "meal schedule": "food schedule",
    # Evacuation center + disaster context expansions (English)
    "where is the shelter": "where is the shelter location",
    "shelter location": "where is the shelter location",
    "where is the evacuation center": "where is the shelter location",
    "evacuation center location": "where is the shelter location",
    "check-in": "registration",
    "check in desk": "registration",
    "check-in desk": "registration",
    "sign in": "registration",
    "sign-in": "registration",
    "where do i sign in": "registration",
    "where do i check in": "registration",
    "registration steps": "registration",
    "registration process": "registration",
    "intake": "registration",
    "id check": "registration",
    "id verification": "registration",
    "lost id": "registration",
    "replacement id": "registration",
    "where do i get a wristband": "wristband",
    "wristband pickup": "wristband",
    "where can i get a bed": "sleeping area",
    "sleeping area": "sleeping area",
    "sleeping zones": "sleeping area",
    "sleeping zone": "sleeping area",
    "cots": "sleeping area",
    "where are the cots": "sleeping area",
    "where can i lie down": "sleeping area",
    "quiet time": "quiet hours",
    "lights off": "quiet hours",
    "lights out time": "quiet hours",
    "curfew time": "curfew",
    "curfew hours": "curfew",
    "bathroom location": "restroom",
    "restroom location": "restroom",
    "toilet location": "restroom",
    "showers location": "showers",
    "shower location": "showers",
    "where can i shower": "showers",
    "laundry": "laundry area",
    "wash clothes": "laundry area",
    "wash my clothes": "laundry area",
    "wash clothes area": "laundry area",
    "where can i wash clothes": "laundry area",
    "where can i wash my clothes": "laundry area",
    "phone charging": "charging",
    "charging station": "charging",
    "charging area": "charging",
    "wifi password": "wi-fi",
    "internet": "wi-fi",
    "where is wi-fi": "wi-fi",
    "is there wi-fi": "wi-fi",
    "where can i eat": "food",
    "where is food": "food",
    "where do i get food": "food",
    "food line": "food",
    "meal time": "food schedule",
    "meal times": "food schedule",
    "mealtime": "food schedule",
    "breakfast time": "food schedule",
    "lunch time": "food schedule",
    "dinner time": "food schedule",
    "food hours": "food schedule",
    "food timetable": "food schedule",
    "meal timetable": "food schedule",
    "water station": "water",
    "drinking water": "water",
    "bottled water": "water",
    "medical": "medical station",
    "first aid": "medical station",
    "nurse": "medical station",
    "doctor": "medical station",
    "clinic": "medical station",
    "medical help": "medical station",
    "hurt": "medical station",
    "injury": "medical station",
    "bleeding": "medical station",
    "burn": "medical station",
    "fever": "medical station",
    "sick": "medical station",
    "medicine refills": "medical station",
    "prescription": "medical station",
    "pharmacy": "medical station",
    "covid": "medical station",
    "flu": "medical station",
    "vaccination": "vaccination",
    "vaccine": "vaccination",
    "shot": "vaccination",
    "mental health support": "mental health",
    "counselor": "mental health",
    "counselling": "mental health",
    "psych support": "mental health",
    "panic": "mental health",
    "anxiety": "mental health",
    "security": "safety",
    "unsafe": "safety",
    "danger": "safety",
    "threat": "safety",
    "evacuation route": "evacuation route",
    "evacuation routes": "evacuation route",
    "evac route": "evacuation route",
    "assembly point": "evacuation route",
    "meeting point": "reunification",
    "family reunification": "reunification",
    "reunification desk": "reunification",
    "find my family": "reunification",
    "missing person": "lost person",
    "lost person": "lost person",
    "lost child": "lost person",
    "missing child": "lost person",
    "lost and found": "lost person",
    "pet": "pets",
    "lost pet": "reunification",
    "pet reunification": "reunification",
    "child care": "family services",
    "childcare": "family services",
    "baby care": "family services",
    "infant formula": "family services",
    "diapers": "family services",
    "donation drop off": "donations",
    "donation center": "donations",
    "where to donate": "donations",
    "relief goods": "distribution",
    "supply pickup": "distribution",
    "supplies": "distribution",
    "blankets": "distribution",
    "hygiene kit": "distribution",
    "toiletries": "distribution",
    "clothing": "distribution",
    "transportation": "transportation",
    "bus": "transportation",
    "shuttle": "transportation",
    "pickup point": "transportation",
    "drop off": "transportation",
    "power": "power",
    "electricity": "power",
    "outage": "power",
    "generator": "power",
    "water outage": "water",
    "no water": "water",
    "hazard": "safety",
    "aftershock": "safety",
    "fire": "safety",
    "flood": "safety",
    "earthquake": "safety",
    "typhoon": "safety",
    "storm": "safety",
    "landslide": "safety",
    "evacuation drill": "safety",
    "drill": "safety",
    "sop": "procedures",
    "sops": "procedures",
    "procedure": "procedures",
    "policy": "rules",
    "policies": "rules",
    "rule": "rules",
    "rules": "rules",
    "announcement": "announcements",
    "announcements": "announcements",
    "updates": "announcements",
    "food distribution": "distribution",
    "water distribution": "distribution",
    "hygiene kits": "distribution",
    "child care center": "family services",
    "childcare": "family services",
    "infant formula": "family services",
    "nursing station": "medical station",
    "medical tent": "medical station",
    "capacity": "shelter capacity",
    "overcrowded": "shelter capacity",
    "full shelter": "shelter capacity",
    "bed availability": "sleeping area",
    "available beds": "sleeping area",
    "id replacement": "registration",
    "replace id": "registration",
    "lost id": "registration",
    "evacuation drill": "safety",
    "emergency drill": "safety",
    "route change": "transportation",
    "bus reroute": "transportation",
    "shelter hours": "hours",
    "curfew enforcement": "curfew",
    "security check": "security",
}

_LANG_SYNONYMS = {
    # Spanish
    "es": {
        "bandería": "laundry area",
        "banderia": "laundry area",
        "lavanderia": "laundry area",
        "lavandería": "laundry area",
        "área de lavado": "laundry area",
        "lavar la ropa": "wash clothes",
        "ropa sucia": "dirty clothes",
        "ducha": "showers",
        "baño": "restroom",
        "sanitario": "restroom",
        "cargar el teléfono": "charging",
        "carga de teléfono": "charging",
        "wifi": "wi-fi",
        "registro": "registration",
        "inscribirme": "registration",
        "pulsera": "wristband",
        "primeros auxilios": "medical station",
        "clínica": "medical station",
        "médico": "medical",
        "camas": "beds",
        "zona de dormir": "sleeping area",
        "refugio": "shelter",
        "centro de evacuación": "evacuation center",
        "transporte": "transportation",
        "autobús": "bus",
        "camion": "bus",
        "perdido": "lost person",
        "objetos perdidos": "lost person",
        "anuncios": "announcements",
        "voluntario": "volunteer",
        "donaciones": "donations",
        "distribución": "distribution",
        "toque de queda": "curfew",
        "horas de silencio": "quiet hours",
        "reglas": "rules",
        "políticas": "rules",
        "procedimientos": "procedures",
        "niño perdido": "lost person",
        "niña perdida": "lost person",
        "reunificación familiar": "reunification",
        "seguridad": "safety",
        "ruta de evacuación": "evacuation route",
        "corte de luz": "power",
        "electricidad": "power",
        "salud mental": "mental health",
        "consejería": "mental health",
        "psicológico": "mental health",
        "psicologico": "mental health",
        "vacunación": "vaccination",
        "vacunacion": "vaccination",
        "ayuda legal": "legal assistance",
        "abogado": "legal assistance",
        "reunificación de mascotas": "reunification",
        "reunificacion de mascotas": "reunification",
        "entrega de donaciones": "donations",
        "horario de donaciones": "donations",
        "horario de distribución": "distribution",
        "horario de distribucion": "distribution",
        "distribución de comida": "distribution",
        "distribucion de comida": "distribution",
        "distribución de agua": "distribution",
        "distribucion de agua": "distribution",
        "kits de higiene": "distribution",
        "cuidado infantil": "family services",
        "fórmula infantil": "family services",
        "formula infantil": "family services",
        "capacidad": "shelter capacity",
        "sobrepoblado": "shelter capacity",
        "albergue lleno": "shelter capacity",
        "camas disponibles": "sleeping area",
        "reemplazo de identificación": "registration",
        "reemplazo de id": "registration",
        "id perdida": "registration",
        "simulacro de evacuación": "safety",
        "cambio de ruta": "transportation",
        "desvío de bus": "transportation",
        "horario del refugio": "hours",
        "control de seguridad": "security",
        "comida": "food",
        "horario de comidas": "food schedule",
    },
    # German
    "de": {
        "wäsche": "laundry",
        "waschraum": "laundry area",
        "wäschebereich": "laundry area",
        "dusche": "showers",
        "toilette": "restroom",
        "wc": "restroom",
        "handy laden": "charging",
        "handyaufladen": "charging",
        "wifi": "wi-fi",
        "registrierung": "registration",
        "anmeldung": "registration",
        "armband": "wristband",
        "erste hilfe": "medical station",
        "klinik": "medical station",
        "arzt": "medical",
        "betten": "beds",
        "schlafbereich": "sleeping area",
        "unterkunft": "shelter",
        "evakuierungszentrum": "evacuation center",
        "transport": "transportation",
        "bus": "bus",
        "vermisst": "lost person",
        "verloren": "lost person",
        "durchsagen": "announcements",
        "freiwilliger": "volunteer",
        "spenden": "donations",
        "ausgabe": "distribution",
        "ausgangssperre": "curfew",
        "ruhezeiten": "quiet hours",
        "regeln": "rules",
        "richtlinien": "rules",
        "verfahren": "procedures",
        "vermisstes kind": "lost person",
        "familienzusammenführung": "reunification",
        "sicherheit": "safety",
        "evakuierungsroute": "evacuation route",
        "stromausfall": "power",
        "strom": "power",
        "psychische gesundheit": "mental health",
        "beratung": "mental health",
        "impfung": "vaccination",
        "impfungen": "vaccination",
        "rechtshilfe": "legal assistance",
        "anwalt": "legal assistance",
        "haustierzusammenführung": "reunification",
        "spendenabgabe": "donations",
        "spendenzeiten": "donations",
        "ausgabezeiten": "distribution",
        "lebensmittelverteilung": "distribution",
        "wasserverteilung": "distribution",
        "hygienekits": "distribution",
        "kinderbetreuung": "family services",
        "säuglingsnahrung": "family services",
        "suglingsnahrung": "family services",
        "kapazität": "shelter capacity",
        "überfüllt": "shelter capacity",
        "voll": "shelter capacity",
        "freie betten": "sleeping area",
        "ersatz für ausweis": "registration",
        "ausweis verloren": "registration",
        "evakuierungsübung": "safety",
        "routenänderung": "transportation",
        "bus umleitung": "transportation",
        "öffnungszeiten": "hours",
        "sicherheitskontrolle": "security",
        "essen": "food",
        "essenszeit": "food schedule",
    },
    # French
    "fr": {
        "blanchisserie": "laundry area",
        "zone de lavage": "laundry area",
        "laver les vêtements": "wash clothes",
        "douche": "showers",
        "toilettes": "restroom",
        "wc": "restroom",
        "charger le téléphone": "charging",
        "recharger": "charging",
        "wifi": "wi-fi",
        "inscription": "registration",
        "enregistrer": "registration",
        "bracelet": "wristband",
        "premiers secours": "medical station",
        "clinique": "medical station",
        "médical": "medical",
        "lits": "beds",
        "zone de sommeil": "sleeping area",
        "refuge": "shelter",
        "centre d'évacuation": "evacuation center",
        "transport": "transportation",
        "bus": "bus",
        "perdu": "lost person",
        "objets perdus": "lost person",
        "annonces": "announcements",
        "bénévole": "volunteer",
        "dons": "donations",
        "distribution": "distribution",
        "couvre-feu": "curfew",
        "heures de silence": "quiet hours",
        "règles": "rules",
        "politiques": "rules",
        "procédures": "procedures",
        "enfant perdu": "lost person",
        "réunification familiale": "reunification",
        "sécurité": "safety",
        "route d'évacuation": "evacuation route",
        "panne de courant": "power",
        "électricité": "power",
        "santé mentale": "mental health",
        "conseil": "mental health",
        "vaccination": "vaccination",
        "aide juridique": "legal assistance",
        "avocat": "legal assistance",
        "réunification des animaux": "reunification",
        "reunification des animaux": "reunification",
        "dépôt de dons": "donations",
        "depot de dons": "donations",
        "horaires des dons": "donations",
        "horaires de distribution": "distribution",
        "distribution de nourriture": "distribution",
        "distribution d'eau": "distribution",
        "kits d'hygiène": "distribution",
        "kits d'hygiene": "distribution",
        "garde d'enfants": "family services",
        "lait infantile": "family services",
        "capacité": "shelter capacity",
        "surchargé": "shelter capacity",
        "complet": "shelter capacity",
        "lits disponibles": "sleeping area",
        "remplacement de pièce d'identité": "registration",
        "carte d'identité perdue": "registration",
        "exercice d'évacuation": "safety",
        "changement d'itinéraire": "transportation",
        "détournement de bus": "transportation",
        "heures d'ouverture": "hours",
        "contrôle de sécurité": "security",
        "repas": "food",
        "horaire des repas": "food schedule",
    },
    # Japanese
    "ja": {
        "洗濯": "laundry",
        "洗濯場所": "laundry area",
        "洗濯エリア": "laundry area",
        "シャワー": "showers",
        "トイレ": "restroom",
        "充電": "charging",
        "wifi": "wi-fi",
        "登録": "registration",
        "受付": "registration",
        "リストバンド": "wristband",
        "応急処置": "medical station",
        "診療所": "medical station",
        "医療": "medical",
        "ベッド": "beds",
        "寝る場所": "sleeping area",
        "寝室": "sleeping area",
        "避難所": "shelter",
        "避難センター": "evacuation center",
        "交通": "transportation",
        "バス": "bus",
        "行方不明": "lost person",
        "落とし物": "lost person",
        "お知らせ": "announcements",
        "ボランティア": "volunteer",
        "寄付": "donations",
        "配布": "distribution",
        "門限": "curfew",
        "消灯": "quiet hours",
        "静かな時間": "quiet hours",
        "規則": "rules",
        "手順": "procedures",
        "迷子": "lost person",
        "家族再会": "reunification",
        "安全": "safety",
        "避難経路": "evacuation route",
        "停電": "power",
        "電気": "power",
        "心のケア": "mental health",
        "カウンセリング": "mental health",
        "予防接種": "vaccination",
        "ワクチン": "vaccination",
        "法律相談": "legal assistance",
        "弁護士": "legal assistance",
        "ペット再会": "reunification",
        "寄付受付": "donations",
        "寄付の時間": "donations",
        "配布時間": "distribution",
        "食料配布": "distribution",
        "水の配布": "distribution",
        "衛生キット": "distribution",
        "子どもケア": "family services",
        "乳児用ミルク": "family services",
        "収容人数": "shelter capacity",
        "混雑": "shelter capacity",
        "満員": "shelter capacity",
        "空いているベッド": "sleeping area",
        "身分証の再発行": "registration",
        "身分証をなくした": "registration",
        "避難訓練": "safety",
        "ルート変更": "transportation",
        "バス迂回": "transportation",
        "開所時間": "hours",
        "セキュリティチェック": "security",
        "食事": "food",
        "食事時間": "food schedule",
    },
}


def normalize_query(text: str, lang: str = "en") -> str:
    """Lowercase, trim, collapse whitespace, then duplicated words, apply hub corrections."""
    if not text or not text.strip():
        return ""
    result = text.lower().strip()
    result = _WHITESPACE.sub(" ", result).strip()
    result = _DUPLICATE_WORD.sub(r"\1", result)
    # Apply language-specific synonyms to inject English domain terms
    if lang and lang in _LANG_SYNONYMS:
        for wrong, right in _LANG_SYNONYMS[lang].items():
            # Use word boundaries for Latin scripts; simple replace for CJK
            if re.search(r"[a-záéíóúüñàâçèêëîïôûùüÿœ]", wrong):
                result = re.sub(rf"\b{re.escape(wrong)}\b", right, result)
            else:
                result = result.replace(wrong, right)
    for wrong, right in _HUB_CORRECTIONS.items():
        result = result.replace(wrong, right)
    result = _WHITESPACE.sub(" ", result).strip()
    return result
